<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SimuladorDeObjetos.BusinessLogic\SimuladorDeObjetos.BusinessLogic.csproj" />
      <ProjectReference Include="..\SimuladorDeObjetos.Infrastructure\SimuladorDeObjetos.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="DTOs\Class1Dto.cs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.0.0" />
    </ItemGroup>

</Project>
