// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimuladorDeObjetos.Infrastructure;

#nullable disable

namespace SimuladorDeObjetos.Infrastructure.Migrations
{
    [DbContext(typeof(SimuladorDbContext))]
    [Migration("20250614155759_AddPolimorfismoSupport")]
    partial class AddPolimorfismoSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AttributeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accessibility")
                        .HasColumnType("int");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConcreteTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ConcreteTypeId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("Domain.Entities.ClassModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAbstract")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BaseClassId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Domain.Entities.InterfaceMethodModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InterfaceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InterfaceId");

                    b.ToTable("InterfaceMethodModels");
                });

            modelBuilder.Entity("Domain.Entities.InterfaceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ClassModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClassModelId");

                    b.ToTable("InterfaceModels");
                });

            modelBuilder.Entity("Domain.Entities.LocalVarModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConcreteTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConcreteTypeId");

                    b.HasIndex("MethodId");

                    b.ToTable("LocalVars");
                });

            modelBuilder.Entity("Domain.Entities.MethodCallModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("ConcreteParameterTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentMethodId");

                    b.ToTable("MethodCalls");
                });

            modelBuilder.Entity("Domain.Entities.MethodModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accessibility")
                        .HasColumnType("int");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAbstract")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReturnType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Methods");
                });

            modelBuilder.Entity("Domain.Entities.NamespaceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Namespaces");
                });

            modelBuilder.Entity("Domain.Entities.ParamModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConcreteTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("InterfaceMethodModelId")
                        .HasColumnType("int");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConcreteTypeId");

                    b.HasIndex("InterfaceMethodModelId");

                    b.HasIndex("MethodId");

                    b.ToTable("Params");
                });

            modelBuilder.Entity("MethodCallConcreteParameters", b =>
                {
                    b.Property<Guid>("ConcreteParametersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MethodCallModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConcreteParametersId", "MethodCallModelId");

                    b.HasIndex("MethodCallModelId");

                    b.ToTable("MethodCallConcreteParameters");
                });

            modelBuilder.Entity("Domain.Entities.AttributeModel", b =>
                {
                    b.HasOne("Domain.Entities.ClassModel", "Class")
                        .WithMany("Attributes")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ClassModel", "ConcreteType")
                        .WithMany()
                        .HasForeignKey("ConcreteTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Class");

                    b.Navigation("ConcreteType");
                });

            modelBuilder.Entity("Domain.Entities.ClassModel", b =>
                {
                    b.HasOne("Domain.Entities.ClassModel", "BaseClass")
                        .WithMany()
                        .HasForeignKey("BaseClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseClass");
                });

            modelBuilder.Entity("Domain.Entities.InterfaceMethodModel", b =>
                {
                    b.HasOne("Domain.Entities.InterfaceModel", null)
                        .WithMany("Methods")
                        .HasForeignKey("InterfaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Entities.InterfaceModel", b =>
                {
                    b.HasOne("Domain.Entities.ClassModel", null)
                        .WithMany("ImplementedInterfaces")
                        .HasForeignKey("ClassModelId");
                });

            modelBuilder.Entity("Domain.Entities.LocalVarModel", b =>
                {
                    b.HasOne("Domain.Entities.ClassModel", "ConcreteType")
                        .WithMany()
                        .HasForeignKey("ConcreteTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.MethodModel", "Method")
                        .WithMany("Vars")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConcreteType");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Domain.Entities.MethodCallModel", b =>
                {
                    b.HasOne("Domain.Entities.MethodModel", "ParentMethod")
                        .WithMany("MethodsCalled")
                        .HasForeignKey("ParentMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentMethod");
                });

            modelBuilder.Entity("Domain.Entities.MethodModel", b =>
                {
                    b.HasOne("Domain.Entities.ClassModel", "Class")
                        .WithMany("Methods")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Domain.Entities.NamespaceModel", b =>
                {
                    b.HasOne("Domain.Entities.NamespaceModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.ParamModel", b =>
                {
                    b.HasOne("Domain.Entities.ClassModel", "ConcreteType")
                        .WithMany()
                        .HasForeignKey("ConcreteTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.InterfaceMethodModel", null)
                        .WithMany("Parameters")
                        .HasForeignKey("InterfaceMethodModelId");

                    b.HasOne("Domain.Entities.MethodModel", "Method")
                        .WithMany("Params")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConcreteType");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("MethodCallConcreteParameters", b =>
                {
                    b.HasOne("Domain.Entities.ClassModel", null)
                        .WithMany()
                        .HasForeignKey("ConcreteParametersId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.MethodCallModel", null)
                        .WithMany()
                        .HasForeignKey("MethodCallModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ClassModel", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("ImplementedInterfaces");

                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Domain.Entities.InterfaceMethodModel", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Domain.Entities.InterfaceModel", b =>
                {
                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Domain.Entities.MethodModel", b =>
                {
                    b.Navigation("MethodsCalled");

                    b.Navigation("Params");

                    b.Navigation("Vars");
                });

            modelBuilder.Entity("Domain.Entities.NamespaceModel", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
